[application]

[web.app]
# HTML title tag content
title = "portfolio"
# Set base_path to empty string to serve from root URL

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
  "/assets/styling/main.css",
  "/assets/tailwind.css",
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
